// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Belt_Debug = require("bs-platform/lib/js/belt_Debug.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var User$ReactTemplate = require("./User.bs.js");

Belt_Debug.setupChromeDebugger(/* () */0);

var component = ReasonReact.statelessComponent("App");

var user = /* record */Block.record([
    "name",
    "age"
  ], [
    "Corentin",
    14
  ]);

var data = " {\n  \"name\": \"Corentin\",\n  \"age\":   14\n} ";

var json = Json.parseOrRaise(data);

var res_000 = /* name */Json_decode.field("name", Json_decode.string, json);

var res_001 = /* age */Json_decode.field("age", (function (param) {
        return Json_decode.optional(Json_decode.$$int, param);
      }), json);

var res = /* record */Block.record([
    "name",
    "age"
  ], [
    res_000,
    res_001
  ]);

var match = res_001;

console.log(match !== undefined ? String(match) : "empty");

function make(_children) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function (_self) {
                return ReasonReact.element(undefined, undefined, User$ReactTemplate.make(user, /* array */[]));
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* jsElementWrapped */13]
          ]);
}

exports.component = component;
exports.user = user;
exports.data = data;
exports.res = res;
exports.make = make;
/*  Not a pure module */
